// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZGFJWqvZieYl5jOSa0nNNv2K3yq9chVo',
    appId: '1:176538167424:web:d15a84898014ff0dea9e65',
    messagingSenderId: '176538167424',
    projectId: 'spotify0101-b150b',
    authDomain: 'spotify0101-b150b.firebaseapp.com',
    storageBucket: 'spotify0101-b150b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqySxBwUoD85kLpMYMBC5SVTjm1or6ffY',
    appId: '1:176538167424:android:142f482eff6af1ebea9e65',
    messagingSenderId: '176538167424',
    projectId: 'spotify0101-b150b',
    storageBucket: 'spotify0101-b150b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaXp-4dTXX5cPh6UG-ibhX8kLW1epNj8s',
    appId: '1:176538167424:ios:a9340170ebc1d21dea9e65',
    messagingSenderId: '176538167424',
    projectId: 'spotify0101-b150b',
    storageBucket: 'spotify0101-b150b.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaXp-4dTXX5cPh6UG-ibhX8kLW1epNj8s',
    appId: '1:176538167424:ios:a9340170ebc1d21dea9e65',
    messagingSenderId: '176538167424',
    projectId: 'spotify0101-b150b',
    storageBucket: 'spotify0101-b150b.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZGFJWqvZieYl5jOSa0nNNv2K3yq9chVo',
    appId: '1:176538167424:web:fedb77bc7a1d3351ea9e65',
    messagingSenderId: '176538167424',
    projectId: 'spotify0101-b150b',
    authDomain: 'spotify0101-b150b.firebaseapp.com',
    storageBucket: 'spotify0101-b150b.firebasestorage.app',
  );
}
